# Generated by Django 4.2 on 2025-04-19 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mealplan_mealitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
